ViewModels/GridCollectionItemViewModel.cs
using Bmerketo_WebApp.Models.Dtos;
using Bmerketo_WebApp.Models.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;

namespace Bmerketo_WebApp.ViewModels;

public class GridCollectionItemViewModel
{
	public string Id { get; set; } = null!;
	public string Title { get; set; } = null!;
	public string? ImageUrl { get; set; }
    [Column(TypeName = "money")]
    public decimal? Price { get; set; } = null!;
	public string? Description { get; set; }

	public IEnumerable<Product> products { get; set; } = new List<Product>();
	
}

ViewModels/GridCollectionViewModel.cs
namespace Bmerketo_WebApp.ViewModels;

public class GridCollectionViewModel
{
	public string Title { get; set; } = null!;
	public string Category { get; set; } = null!;
	public bool LoadMore { get; set; } = false;

	public List<string> Categories { get; set; } = new List<string>();
	public List<GridCollectionItemViewModel> GridItems { get; set; } = new List<GridCollectionItemViewModel>();

}

ViewModels/LoginViewModel.cs
using Bmerketo_WebApp.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace Bmerketo_WebApp.ViewModels;

public class LoginViewModel
{
	[Display(Name = "Email*")]
	[Required(ErrorMessage = "E-mail is required.")]
	[DataType(DataType.EmailAddress)]
    [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Invalid Password or Email.")]
    public string Email { get; set; } = null!;

	[Display(Name = "Password*")]
	[Required(ErrorMessage = "Password is required.")]
	[DataType(DataType.Password)]
    
    public string Password { get; set; } = null!;
	public bool RememberMe { get; set; } = false;


}

ViewModels/TopSellingViewModels.cs
namespace Bmerketo_WebApp.ViewModels;

public class TopSellingViewModels
{
	public string Title { get; set; } = null!;
	public List<GridCollectionItemViewModel> GridItems { get; set; } = new List<GridCollectionItemViewModel>();
}

Controllers/AccountController.cs
using Bmerketo_WebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace Bmerketo_WebApp.Controllers;

public class AccountController : Controller
{
	private readonly UserService _userService;

	public AccountController(UserService userService)
	{
		_userService = userService;
	}
	

	public IActionResult Register()
    {
        return View();
    }

	[Authorize]
	public IActionResult Index()
	{
		return View();
	}

	
}

Controllers/ContactsController.cs
using Bmerketo_WebApp.Helpers.Repositories;
using Bmerketo_WebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bmerketo_WebApp.Controllers;

public class ContactsController : Controller
{
    private readonly ContactFormRepository _contactFormRepository;

    public ContactsController(ContactFormRepository contactFormRepository)
    {
        _contactFormRepository = contactFormRepository;
    }

    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Index(ContactFormViewModel viewModel)
    {
        if (ModelState.IsValid) 
        {
            await _contactFormRepository.AddAsync(viewModel);
            return RedirectToAction("Index");
        }
        return View(viewModel);
    }
}

Controllers/LoginController.cs
using Bmerketo_WebApp.Helpers.Services;
using Bmerketo_WebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Bmerketo_WebApp.Controllers;

public class LoginController : Controller
{
	private readonly AuthenticationService _authenticationService;

	public LoginController(AuthenticationService authenticationService)
	{
		_authenticationService = authenticationService;
	}

	public IActionResult Index()
	{
		return View();
	}
	[HttpPost]
	public async Task<IActionResult> Index(LoginViewModel viewModel)
	{
		if (ModelState.IsValid)
		{
			if (await _authenticationService.LoginAsync(viewModel))
			{
				return RedirectToAction("Index", "Account");
			}
			ModelState.AddModelError("", "Invalid email or password. Please try again.");
		}
		return View(viewModel);
	}

    [Authorize]
    public async Task<IActionResult> Logout()
    {
		if (await _authenticationService.SignOutAsync(User))
			return LocalRedirect("/");
		return RedirectToAction("Index");
    }
}

Controllers/RegisterController.cs
using Bmerketo_WebApp.Helpers.Services;
using Bmerketo_WebApp.Models.Entities;
using Bmerketo_WebApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bmerketo_WebApp.Controllers;

public class RegisterController : Controller
{
	private readonly UserManager<UserEntity> _userManager;
	private readonly AuthenticationService _authenticationService;

	public RegisterController(UserManager<UserEntity> userManager, AuthenticationService authenticationService)
	{
		_userManager = userManager;
		_authenticationService = authenticationService;
	}

	public IActionResult Index()
	{
		return View();
	}
	[HttpPost]
	public async Task<IActionResult> Index(UserRegisterViewModel viewModel)
	{
		if (ModelState.IsValid)
		{
			if (!await _userManager.Users.AnyAsync(x => x.Email == viewModel.Email))
			{
				if (await _authenticationService.SignUpAsync(viewModel))
					return RedirectToAction("Index", "Login");
			}
			ModelState.AddModelError("", "A user with the provided email already exists.");
		}
		return View(viewModel);
	}
}

Views/Partials/_Account.cshtml
<partial name="/Views/Partials/_Login.cshtml" />

Views/Partials/_AdminChangeRole.cshtml
@inject UserAdminService userAdminService
@{
    ViewData["Title"] = "Backoffice";
}

<div class="container" style="padding-top: 200px;">
    <partial name="/Views/Partials/_AdminSidbar.cshtml" />
    @foreach (var user in await userAdminService.GetUsersAsync())
    {
        <div class="mb-5">
            <div>
                @user.Email
                @user.FirstName
                @user.LastName
                (
                @foreach (var roleName in user.RoleNames)
                {
                    <span>@roleName</span>
                }
                )
            </div>
            <div>
                @if (User.IsInRole("admin")) // Kontrollera om den aktuella användaren har admin-rollen
                {

                    <form method="post" asp-action="ChangeRole" asp-controller="Admin">
                        <input type="hidden" name="userId" value="@user.Id" />
                        <select name="newRole" asp-for="@user.NewRole">
                            <option value="Select">Select</option>
                            <option value="admin">admin</option>
                            <option value="user">user</option>
                            <!-- Lägg till fler rollalternativ om det behövs -->
                        </select>
                        <button type="submit">Ändra roll</button>
                    </form>
                }
            </div>
        </div>
    }
</div>

Views/Partials/_AdminSidbar.cshtml
@{
	ViewData["Title"] = "backoffice-systemet";
}
<div class="sidebar">
    <ul class="sidebar-menu">
        <li>
            <a asp-controller="Account" asp-action="Register">
                <i class="fa fa-user-plus"></i>
                Lägg till ny användare
            </a>
        </li>
        <li>
            <a asp-controller="Admin" asp-action="AddProduct">
                <i class="fa fa-plus-circle"></i>
                Lägg till ny produkt
            </a>
        </li>
        <li>
            <a asp-controller="Admin" asp-action="ChangeRole">
                <i class="fa fa-exchange-alt"></i>
                Byt användarroll
            </a>
        </li>
    </ul>
</div>

Views/Partials/_ContactForm.cshtml
@model ContactFormViewModel 
<section class="breadcrumb">
    <div class="container">
        <div class="content">
            <div class="title">
                <h1>CONTACT</h1>
            </div>
            <ul>
                <li>HOME</li>
                <li>CONTACT</li>
            </ul>
        </div>
    </div>
</section>

<section class="contact-form">
    <div class="container">
        <div class="title">Write something</div>
        <form asp-action="Index" asp-controller="Contacts" method="post" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-denger"></div>
            <div class="name form-group">
                <label asp-for="Name">Your Name*</label>
                <input id="Name" asp-for="Name" type="text" class="" onkeyup="validateText(event)" required>
                <small><span asp-validation-for="Name" class="text-denger"></span></small>
            </div>
            <div class="email form-group">
                <label asp-for="Email">Your Email*</label>
                <input id="Email" asp-for="Email" type="text" class="" onkeyup="validateEmail(event)">
                <small><span asp-validation-for="Email" class="text-denger"></span></small>
            </div>
            <div class="phoneNumber form-group">
                <label asp-for ="PhoneNumber">Phone Number (optional)</label>
                <input asp-for="PhoneNumber" id="PhoneNumber" type="text" onkeyup="validateText(event)">
            </div>
            <div class="companyName form-group">
                <label asp-for="Company">Company (optional)</label>
                <input asp-for="Company" id="Company" type="text" onkeyup="validateText(event)">
            </div>
            <div class="message form-group">
                <label asp-for="Message">Message*</label>
                <textarea asp-for="Message" id="Message" class="" onkeyup="validateText(event)"></textarea>
                <small><span asp-validation-for="Message" class="text-denger"></span></small>
          
            </div>
            <div class="terms form-checkbox-group">
                <label class="custom-checkbox">
                    Save my name, email in the this browser for the next time I comment.
                    <input type="checkbox" checked="checked">
                    <span class="checkmark"></span>
                </label>
            </div>
            <button class="btn-theme">Submit</button>
        </form>
    </div>
</section>

Views/Partials/_Footer.cshtml
<footer>
    <div class="container">
        © @DateTime.Now.Year bmerketo. All right reserved.
    </div>
</footer>

Views/Partials/_GridCollection.cshtml
@model ProductsIndexViewModel
@*@model GridCollectionViewModel*@
@inject ProductRepository productRepo


@{
    //ViewData["Title"] =  Model.Title;
}


    <section class="grid-collection">
        <div class="container">
       
        @{
            var visitedCategories = new HashSet<string>(); // Skapar en HashSet för att lagra unika kategorier
        }

        @foreach (var product in await productRepo.GetAsync())
        {
            <div>
                @if (product.ProductRelationshipEntities.Count > 0)
                {
                    foreach (var category in product.ProductRelationshipEntities)
                    {
                        // Kolla om kategorin redan har besökts
                        if (!visitedCategories.Contains(category.Category.CategoryName))
                        {
                            <span asp-route-id="@product.Id" class="me-2">@category.Category.CategoryName</span>
                            visitedCategories.Add(category.Category.CategoryName); // Lägg till kategorin i HashSet
                        }
                    }
                   
                }
                
            </div>
        }

            <div class="grid">
            @foreach (var product in await productRepo.GetAsync())
            {
                <a asp-controller="products" asp-action="details" asp-route-id="@product.Id" class="collection-item">

                    <div class="collection-content">
                    @if (product.ProductRelationshipEntities.Count == 0)
                    {
                        <span>No images found</span>
                    }
                    else
                    {
                        var firstImage = product.ProductRelationshipEntities.FirstOrDefault();
                        if (firstImage != null)
                        {
                            <div>
                                <img src="~/images/products/@firstImage.ImageUrl.ImageUrlName" width="270px" />
                            </div>
                        }
                        else
                        {
                            <span>Image URL is null</span>
                        }
                     
                    }
                        <div class="title">@product.Title</div>

                        <div class="body">
                            
                            <div class="info">
                                <div class="price">$@string.Format("{0:0.00}", product.Price)</div>

                                <i class="add-cart fa-regular fa-cart-plus"></i>
                            </div>
                        </div>

              </div>
                </a>
                
            }
            </div>
            <div class="load-more">
                <button class="btn-outline-white">LOAD MORE <i class="fa-solid fa-rotate-right"></i></button>
            </div>
       
            <button id="load-more-btn" class="btn-outline-white">LOAD MORE <i class="fa-solid fa-rotate-right"></i></button>
        </div>
    
    </section>
}

Views/Partials/_Header.cshtml
<header>
    <div class="container">
        <div class="logo"><img src="../../images/logo.svg" alt="">bmerketo</div>
        
        @if (signInManager.IsSignedIn(User) && User.IsInRole("admin"))
        {
            <a asp-controller="admin" asp-action="index">Admin</a>
        }
        <nav id="menu" class="menu-links">
            <a class="link" asp-controller="home" asp-action="index">HOME</a>
            <a class="link" asp-controller="products" asp-action="index">PRODUCTS</a>
            <a class="link" asp-controller="contacts" asp-action="index">CONTACT</a>
        </nav>
        <nav class="menu-icons">
            <a class="link" asp-controller="products" asp-action="search"><i class="fa-regular fa-search"></i></a>

            @if (signInManager.IsSignedIn(User))
            {
                <a asp-controller="account" asp-action="index">@(User.FindFirst("DisplayName")?.Value)</a>
                <a class="link" asp-controller="login" asp-action="logout">Logout</a>
            }
            else
            {
                <a class="link" asp-controller="login" asp-action="index">Login</a>
            }
            
            <a class="link" asp-controller="shopping" asp-action="chart"><i class="fa-solid fa-cart-shopping"></i></a>
        </nav>
        <div class="toggle">
            <button class="btn-toggle btn-outline-white" data-option="toggle" data-target="#menu">
                <i id="icon" class="fa-regular fa-bars"></i>
            </button>
        </div>
    </div>
</header>

Views/Partials/_Register.cshtml
@model UserRegisterViewModel
<div class="register">
    <div class="container">
        <form asp-action="Index" asp-controller="Register" method="post" id="register-form" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-denger"></div>
            <p>Plase Register Your new Account</p>
            <div class="f-l-name">
                <div class="form-group">
                    <label asp-for="FirstName"></label>
                    <input id="FirstName" asp-for="FirstName" onkeyup="validateText(event)">
                    <small><span asp-validation-for="FirstName" class="text-denger"></span></small>
                </div>
                <div class="form-group">
                    <label asp-for="LastName"></label>
                    <input id="LastName" asp-for="LastName" onkeyup="validateText(event)">
                    <small><span asp-validation-for="LastName" class="text-denger"></span></small>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="StreetName"></label>
                <input id="StreetName" asp-for="StreetName" onkeyup="validateText(event)">
                <small><span asp-validation-for="StreetName" class="text-denger"></span></small>
            </div>
            <div class="postal-city">
                <div class="form-group">
                    <label asp-for="PostalCode"></label>
                    <input id="PostalCode" asp-for="PostalCode" onkeyup="validateText(event)">
                    <small><span asp-validation-for="PostalCode" class="text-denger"></span></small>
                </div>

                <div class="form-group">
                    <label asp-for="City"></label>
                    <input id="City" asp-for="City" onkeyup="validateText(event)">
                    <small><span asp-validation-for="City" class="text-denger"></span></small>
                </div>
            </div>
            <div class="option">
                <div class="form-group">
                    <label asp-for="MobileNumber"></label>
                    <input id="MobileNummber" asp-for="MobileNumber" onkeyup="validateText(event)">
                    <small><span asp-validation-for="MobileNumber" class="text-denger"></span></small>
                </div>
                <div class="form-group">
                    <label asp-for="Company"></label>
                    <input id="Company" asp-for="Company" onkeyup="validateText(event)">
                    <small><span asp-validation-for="Company" class="text-denger"></span></small>
                </div>
            </div>      
            <div class="form-group">
                <label asp-for="Email"></label>
                <input id="Email" asp-for="Email" onkeyup="validateEmail(event)">
                <small><span asp-validation-for="Email" class="text-denger"></span></small>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input id="Password" asp-for="Password" onkeyup="validatePassword(event)">
                <small><span asp-validation-for="Password" class="text-denger"></span></small>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input id="ConfirmPassword" asp-for="ConfirmPassword" onkeyup="validatePassword(event)">
                <small><span asp-validation-for="ConfirmPassword" class="text-denger"></span></small>
            </div>
            <label class="custom-checkbox">
                I have read and accepts the terms and agreements
                <input type="checkbox" checked="checked">
                <span class="checkmark"></span>
            </label>
            <div class="buttens">
                <button class="btn-theme btn-left" type="submit">Registrera</button>
                <a asp-controller="login" asp-action="index" class="btn-theme btn-right link">Login</a>
            </div>
            
        </form>

    </div>
</div>

Views/Partials/_Showcase.cshtml
@model ProductsIndexViewModel
@inject ProductRepository productRepo
@{
    var showcase = showcaseService.GetLatest();
    var product = await productRepo.GetAsync();
    
}

@if (showcase != null)
   
{
    
    <section class="showcase">
        <div class="container">
            <div class="content">
                <div class="ingress">@showcase?.Ingress</div>
                <div class="title">@showcase?.Title</div>
                @if (!string.IsNullOrEmpty(showcase?.Button?.Url) && !string.IsNullOrEmpty(@showcase?.Button?.Content))
                {
                    <a href="@showcase?.Button?.Url" class="btn-theme">@showcase?.Button?.Content</a>
                }

            </div>
            <div class="content-image">
                <img src="~/images/products/@product.LastOrDefault()?.ProductRelationshipEntities.LastOrDefault()?.ImageUrl.ImageUrlName" alt="@showcase?.Title">
            </div>
        </div>
    </section>
}

Views/Partials/_TopSelling.cshtml
@model TopSellingViewModels

<section class="top-selling">
    <div class="container-fluid">
        <h1 class="collection-title">@Model.Title</h1>
        <div class="collection-grid">
            @foreach (var item in Model.GridItems.Take(7))
            {
                <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item" />
            }
            <!-- collection-item end -->
        </div>
        <div class="load-more">
            <button class="btn-outline-white me-1"><i class="fa-solid fa-chevron-left"></i></button>
            <button class="btn-outline-white ms-1"><i class="fa-solid fa-chevron-right"></i></button>
        </div>
    </div>
</section>

Views/Partials/_UpToSell.cshtml
@{
	var uptosell = uptosellService.GetLatestOnSale();
}

<section class="up-to-sell">
    <div class="container">
        <div class="collection-grid">
            <div class="item-1">
                <!-- collection-item start -->
                <a href="#" class="collection-item">
                    <img src="@uptosell?.FirstOrDefault()?.ImageUrl" alt="@uptosell?.FirstOrDefault()?.Title">
                    <div class="body">
                        <div class="title">@uptosell?.FirstOrDefault()?.Title</div>
                        <div class="info">
                            <div class="price">$@uptosell?.FirstOrDefault()?.Price</div>
                            <i class="add-cart fa-regular fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                <!-- collection-item end -->
            </div>
            <div class="discover">
                <!-- collection-content start -->
                    <div class="collection-content">
                        <div class="container">
                            <div class="title-red">UP TO SELL</div>
                            <div class="title">50% OFF</div>
                            <div class="ingress">Get the Best Price</div>
                            <div class="text">Get the best daily offer et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren no sea taki</div>
                        <a asp-controller="products" asp-action="discover" class="link">Discover More</a>
                        </div>
                    </div>
                <!-- collection-content end -->
            </div>
            <div class="item-2">
                <!-- collection-item start -->
                <a href="#" class="collection-item">
                    <img src="@uptosell?.LastOrDefault()?.ImageUrl" alt="@uptosell?.LastOrDefault()?.Title">
                    <div class="body">
                        <div class="title">@uptosell?.LastOrDefault()?.Title</div>
                        <div class="info">
                            <div class="price">$@uptosell?.LastOrDefault()?.Price</div>
                            <i class="add-cart fa-regular fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                <!-- collection-item end -->
            </div>
        </div>
    </div>
</section>